# Copy this file to secrets.yaml and fill in the values
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # Base64 encoded Docker config JSON
  # To generate this, run:
  # kubectl create secret docker-registry ghcr-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=<your-github-username> \
  #   --docker-password=<your-github-token> \
  #   --docker-email=<your-email> \
  #   --dry-run=client -o yaml
